# Generated by Django 5.2.11 on 2026-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cidr', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('VPC', 'VPC'), ('CONTAINER', 'Container'), ('EXTERNAL', 'External'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorrelatedFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_key', models.CharField(max_length=255, unique=True)),
                ('client_ip', models.GenericIPAddressField(db_index=True)),
                ('server_ip', models.GenericIPAddressField(db_index=True)),
                ('client_port', models.PositiveIntegerField(blank=True, null=True)),
                ('server_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.PositiveSmallIntegerField(db_index=True)),
                ('flow_count', models.PositiveIntegerField(default=0)),
                ('c2s_packets', models.PositiveBigIntegerField(default=0)),
                ('c2s_bytes', models.PositiveBigIntegerField(default=0)),
                ('s2c_packets', models.PositiveBigIntegerField(default=0)),
                ('s2c_bytes', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('action_counts', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['client_ip', 'server_ip', 'protocol'], name='flows_corre_client__bcea07_idx'), models.Index(fields=['last_seen'], name='flows_corre_last_se_2e548f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlowLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=2)),
                ('account_id', models.CharField(blank=True, max_length=32)),
                ('interface_id', models.CharField(blank=True, max_length=32)),
                ('srcaddr', models.GenericIPAddressField(db_index=True)),
                ('dstaddr', models.GenericIPAddressField(db_index=True)),
                ('srcport', models.PositiveIntegerField(blank=True, null=True)),
                ('dstport', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.PositiveSmallIntegerField(db_index=True)),
                ('packets', models.PositiveBigIntegerField(default=0)),
                ('bytes', models.PositiveBigIntegerField(default=0)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=16)),
                ('log_status', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('raw_line', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['srcaddr', 'dstaddr', 'protocol'], name='flows_flowl_srcaddr_522ad5_idx'), models.Index(fields=['start_time', 'end_time'], name='flows_flowl_start_t_eced06_idx')],
            },
        ),
    ]
