# Generated by Django 5.2.11 on 2026-02-28 02:54

from django.db import migrations, models


def backfill_networkgroup_cidrs(apps, schema_editor):
    NetworkGroup = apps.get_model("flows", "NetworkGroup")
    for group in NetworkGroup.objects.all().iterator():
        cidr = (group.cidr or "").strip()
        if not cidr:
            continue
        if isinstance(group.cidrs, list) and group.cidrs:
            continue
        group.cidrs = [cidr]
        group.save(update_fields=["cidrs"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgroup',
            name='cidrs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='networkgroup',
            name='cidr',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_networkgroup_cidrs, noop_reverse),
    ]
