# Generated by Django 5.2.11 on 2026-03-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_networkgroup_cidrs_alter_networkgroup_cidr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmetadata',
            name='account_owner',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='asset_kind',
            field=models.CharField(choices=[('INSTANCE', 'Instance'), ('ENI', 'ENI'), ('ON_PREM', 'On-Prem'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='availability_zone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='instance_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='instance_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='interface_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='region',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ipmetadata',
            name='state',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
