# Generated by Django 5.2.11 on 2026-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_ipmetadata_account_owner_ipmetadata_asset_kind_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='correlatedflow',
            name='flows_corre_last_se_2e548f_idx',
        ),
        migrations.AlterField(
            model_name='flowlogentry',
            name='ingested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='flowlogentry',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='correlatedflow',
            index=models.Index(fields=['last_seen', 'id'], name='flows_corre_last_se_230f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='flowlogentry',
            index=models.Index(fields=['start_time', 'id'], name='flows_flowl_start_t_ee5bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='flowlogentry',
            index=models.Index(fields=['source', 'start_time'], name='flows_flowl_source_5d8449_idx'),
        ),
    ]
